[package]
name = "random_functions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loop_unwrap = "0.2.0"
serde = "1.0.145"
